## Runs the headless Polyworld tests.

{.warning[UnusedImport]: off.}
import
  test_actioncam,
  test_basic,
  test_bodies,
  test_body_layers,
  test_chrome,
  test_cli,
  test_clickmarks,
  test_controllers,
  test_cta_maps,
  test_cta_nav,
  test_cta_sim,
  test_fixed,
  test_fxmeshes,
  test_gameuis,
  test_gota_content,
  test_gota_replays,
  test_gota_world,
  test_hashes,
  test_hlf_content,
  test_hlf_maps,
  test_hlf_replays,
  test_hlf_sim,
  test_hudlayouts,
  test_inputs,
  test_lvd_content,
  test_lvd_maps,
  test_lvd_replays,
  test_lvd_sim,
  test_nav,
  test_noises,
  test_pathing,
  test_player,
  test_profiles,
  test_rngs,
  test_rtscameras,
  test_tapes,
  test_terrains,
  test_terrainmaps,
  test_aigen_blends,
  test_aigen_splats,
  test_tile_paths,
  test_viewers,
  test_visions

echo "All tests passed"
