' Richard's v63 policy using native, metered array arithmetic.
' Generated by convert.py. Game observations and commands are unchanged.
' DATA initializes once. DIM retains its inclusive BASIC upper bound.
' Matrices are row-major: weights(outputIndex * inputCount + inputIndex).

DATA draftWeights AS fixed32 = _
  -0.252276, 0.208388, 0.165655, -0.077038, -0.307499, 0.393190, _
  -0.041722, -0.247450, -0.267264, 0.060881, 0.000000, -0.056464, _
  -0.558547, 0.238349, 0.148874, -0.351042, 0.022783, 0.133934, _
  -0.148994, -0.127461, 0.000000, -0.404200, 0.140616, -0.413587, _
  -0.093651, -0.294424, -0.233337, -0.138760, 0.163981, -0.185696, _
  -0.139714, -0.291812, 0.252661, 0.220766, -0.066995, 0.046584, _
  -0.074833, 0.282953, -0.316809, 0.260309, 0.498069, 0.607530, _
  -0.054461, 0.000000, 0.185443, 0.307806, 0.073798, 0.095548, _
  -0.624112, -0.128341, 0.116202, -0.113738, 0.022566, 0.000000, _
  0.102318, -0.133625, 0.221801, -0.157735, 1.161687, 0.088798, _
  -0.393505, -0.273026, -0.028371, 0.127856, 0.160424, -0.457565, _
  0.306957, -0.351070, 0.501679, 0.772043, -0.220549, -0.161796, _
  0.448017, -0.150996, 0.136125, 0.178068, 0.000000, 0.247534, _
  -0.188988, -0.238955, 0.883443, 0.034082, 0.088084, 0.000000, _
  0.010408, 0.586454, 0.000000, 0.410493, -0.005734, -0.226131, _
  -0.355937, 0.434671, -0.229144, 0.457953, 0.227879, 0.216607, _
  0.191406, -0.378401, -0.681596, -0.102972, 0.400384, -0.198847, _
  -0.095249, -0.499520, 0.154836, 0.124309, -0.098351, 0.079512, _
  0.896409, 0.000000, -0.105452, -0.086497, -0.053812, 0.204039, _
  -0.676251, 0.027087, -0.196028, 0.195917, -0.317785, 0.000000, _
  -0.397904, 0.182371, 0.046089, 0.192509, 0.418443, -0.254368, _
  0.037337, -0.026151, -0.615030, 0.124070, -0.215150, -0.227015, _
  -0.279421, -0.805966, -0.051813, 0.012569, -0.390292, -0.465863, _
  0.349372, 0.302593, -0.114656, -0.015071, 0.000000, 0.281769, _
  -0.040930, 0.011989, -0.098396, -0.247384, -0.013763, -0.706084, _
  0.050385, -0.037334, 0.000000, 0.244777, -0.186678, -0.303979, _
  0.209267, 0.433826, 0.085857, -0.061916, -0.232312, -0.183645, _
  -0.270940, -0.249030, -0.064811, -0.242457, -0.040038, -0.037761, _
  -0.901328, 0.027995, -0.392084, -0.497526, 0.312257, 0.104801, _
  -0.183950, 0.000000, 0.045312, 0.127481, 0.460752, -0.051012, _
  0.381939, 0.438713, -0.283774, -0.098228, 0.006305, 0.000000, _
  -0.247731, -0.332176, 0.198120, -0.219440, -0.014794, -0.031255, _
  0.727924, 0.905780, 0.451952, 0.593039, 0.580693, 0.784972, _
  0.714471, 0.539523, 0.567051, 0.609534, 0.213345, -0.291630, _
  0.069507, 0.000000, 0.103936, 0.023463, 0.000000, 0.043553, _
  0.061384, 0.061384, -0.226798, 0.100322, 0.193012, 0.121433, _
  0.029843, -0.093964, 0.000000, 0.131395, 0.086036, 0.043553, _
  0.056989, 0.076966, 0.168151, -0.445483, -0.279111, 0.122942, _
  -0.494774, -0.299634, -0.131236, 0.092192, 0.164071, -0.176015, _
  0.002602, 0.310725, -0.538125, 0.274210, 0.488313, -0.038538, _
  0.069213, 0.000000, 0.434066, 0.183095, -0.078561, 0.226950, _
  0.909428, -0.304960, 0.098653, 0.430365, 0.154216, 0.000000, _
  -0.505944, 0.085113, 0.237112, 0.203052, -0.294455, 0.111733, _
  0.787697, 0.595129, 0.080587, -0.130948, 0.222401, 0.450339, _
  0.041381, -0.138733, -0.194858, 0.316302, -0.090298, -1.080760, _
  -0.178166, -0.011497, -0.011433, -0.360402, 0.000000, 0.268030, _
  0.530694, -0.386654, -0.656018, 0.527012, 0.138960, 0.183827, _
  -0.169586, -0.048555, 0.000000, -0.087915, -0.268616, 0.006353, _
  -0.106492, -0.105644, -0.198469, -0.350568, -0.342004, -0.555305, _
  -0.039455, -0.408405, -0.314541, -0.498641, 0.038310, -0.341580, _
  -0.161989, -0.076870, -0.158366, 0.325749, -0.290464, -0.066335, _
  -0.236848, 0.000000, -0.430459, -0.051418, -0.138183, -0.071204, _
  0.001728, -0.269085, -0.168722, -0.023902, 0.052747, 0.000000, _
  -0.193678, -0.219699

DATA draftBias AS fixed32 = _
  -0.252276, 0.220766, 0.306957, -0.102972, -0.279421, -0.242457, _
  0.714471, 0.092192, 0.041381, -0.498641

DATA encoder AS int32 = _
  263, 222, -62, -8, 156, 176, _
  -660, 470, 178, 648, 309, 38, _
  78, -150, 200, 5, -491, 183, _
  -26, 311, 646, 80, 544, 39, _
  255, 126, -23, 117, -25, 585, _
  -305, -320, 118, 235, 32, 21, _
  -234, 656, 93, 602, 414, 439, _
  243, 243, -340, 187, -78, 72, _
  -522, 315, -346, 10, -181, 180, _
  64, 725, -25, 71, 104, -523, _
  -232, -80, -27, -30, -313, -350, _
  -320, -11, 493, -48, -128, 182, _
  -73, -520, -23, 190, 158, -294, _
  61, -155, -122, 280, -28, -22, _
  396, 438, 38, 385, 238, -15, _
  -727, 119, 363, -197, -128, -135, _
  -497, 121, -12, -15, 431, -81, _
  108, -107, 178, -317, -339, 286, _
  230, -103, -293, -141, 714, 388, _
  -197, -213, 109, 384, 214, 562, _
  195, 323, 25, 668, -158, 360, _
  159, 398, 339, -52, -357, -172, _
  110, -22, 646, 125, -453, -365, _
  177, 230, -367, 408, 465, 703, _
  61, 136, 543, 41, -54, 54, _
  122, -158, -130, 204, -64, -508, _
  639, 551, 299, 239, -38, -406, _
  -41, -158, -309, 353, 131, -140, _
  -48, 244, 161, 174, -9, 91, _
  715, -90, 489, 349, 361, 116, _
  -315, -91, -101, 238, -164, 238, _
  -133, 125, 458, 371, 3, 30, _
  203, -106, 482, -345, 302, 932, _
  147, 505, 101, 49, 180, -178, _
  -311, 502, -51, 361, 179, 638, _
  -61, 240, 314, 248, -8, 483, _
  730, 314, 155, 291, -257, 241, _
  543, 9, -66, 411, 470, 170, _
  61, 50, -20, -192, -211, 60, _
  68, -32, -109, -126, -404, 49, _
  543, -90, 554, 445, 341, -324, _
  -471, -27, 378, 114, 861, 381, _
  130, 413, -252, 152, 159, 421, _
  -140, -151, 669, -70, 515, 338, _
  102, 453, -71, 383, 255, -158, _
  195, 441, 133, 189, 264, 82, _
  -702, 275, 91, -190, 47, -505, _
  -288, -299, -56, 716, -16, 78, _
  18, 95, 6, 302, -370, 419, _
  284, 2, -157, 129, 332, 261, _
  -187, 342, -126, -271, -109, -323, _
  149, 43, -690, 236, -95, 383, _
  276, 62, 485, 215, -249, -34, _
  413, 130, 137, 562, 61, 214, _
  123, -49, 121, 69, 190, 856, _
  44, -31, -132, -120, 458, 407, _
  -483, 6, 396, -271, 452, 40, _
  -47, -98, -226, -24, 342, 192, _
  508, -284, 432, 481, 400, -699, _
  108, 103, -31, -289, 548, 208, _
  338, 67, 157, 80, -99, -136, _
  179, -206, 274, -139, 86, 412, _
  33, 278, 594, 651, 160, -271, _
  341, 228, -548, -380, 170, 260, _
  78, 188, 579, -65, 58, -197, _
  173, 208, -353, 354, -48, -264, _
  293, 413, -53, -198

DATA encoderBias AS int32 = _
  18208, 18392, 3752, 19627, 18521, 18435, _
  23325, 19286, 18159, 19073, 18190, 19629, _
  19929, 21374, 18212, 18656

DATA decoder AS int32 = _
  -128, -127, -9, -160, -125, -151, _
  -198, -129, -126, -140, -111, -199, _
  -146, -192, -125, -129, 113, 102, _
  10, 106, 96, 110, 83, 86, _
  101, 96, 95, 62, 124, 115, _
  101, 103, 114, 122, 25, 121, _
  105, 113, 104, 113, 112, 113, _
  102, 86, 104, 132, 98, 113, _
  124, 135, -1, 134, 118, 129, _
  105, 120, 110, 115, 108, 65, _
  116, 119, 124, 124, 111, 115, _
  18, 135, 112, 136, 94, 112, _
  107, 125, 98, 77, 105, 139, _
  114, 111, 118, 123, -6, 122, _
  94, 112, 107, 125, 116, 113, _
  102, 68, 107, 137, 113, 113, _
  102, 104, 17, 120, 107, 107, _
  99, 105, 107, 108, 94, 94, _
  107, 134, 96, 112, 127, 114, _
  43, 132, 111, 125, 106, 120, _
  132, 123, 118, 89, 113, 133, _
  117, 131, 112, 119, 1, 125, _
  110, 130, 105, 116, 115, 109, _
  102, 95, 107, 142, 105, 115, _
  -137, -135, -16, -166, -133, -152, _
  -209, -142, -122, -142, -121, -185, _
  -152, -198, -139, -141, 115, 113, _
  36, 104, 98, 120, 76, 94, _
  107, 122, 97, 66, 133, 122, _
  107, 112, 107, 128, -22, 122, _
  105, 128, 116, 113, 113, 109, _
  99, 103, 97, 152, 108, 119, _
  116, 134, 8, 128, 110, 125, _
  89, 117, 109, 106, 100, 83, _
  115, 114, 114, 111, 125, 129, _
  -7, 136, 117, 137, 124, 118, _
  119, 119, 108, 83, 129, 149, _
  122, 130, 120, 121, -14, 127, _
  100, 106, 113, 117, 110, 112, _
  106, 76, 119, 129, 112, 106, _
  119, 118, -26, 137, 124, 135, _
  105, 124, 123, 129, 114, 132, _
  121, 145, 113, 121, 122, 97, _
  -11, 122, 110, 109, 97, 118, _
  112, 106, 111, 73, 133, 130, _
  112, 123, 133, 140, 12, 135, _
  112, 131, 116, 125, 125, 129, _
  114, 121, 106, 153, 120, 119

DATA decoderBias AS int32 = _
  387878561, 8621915, 9365853, 10032520, 10514535, 10182099, _
  9061429, 10778495, 9785349, 387767339, 9125238, 9920025, _
  9813639, 11515426, 9815518, 11022095, 10193590, 10897366

dim draftScores(9)
dim logits(17)

' Gods of the Arena 2026.9.21.3 compatibility layer.
' Draft a balanced roster, spend ability points, buy back, and keep the
' previously trained neural clock relative to the start of combat.
dim draftF(31)
sub chooseHero()
  if draftTurnId <> selfId then
    exit sub
  end if
  for draftClass = 0 to 9
    draftF(draftClass) = heroAvailable(draftClass)
    draftF(10 + draftClass) = 0
    draftF(20 + draftClass) = 0
  next draftClass
  draftAllyCount = 0
  draftEnemyCount = 0
  for draftPlayer = 0 to draftPlayerCount() - 1
    draftPicked = draftedClass(draftPlayerId(draftPlayer))
    if draftPicked >= 0 then
      if draftPlayerTeam(draftPlayer) = selfTeam then
        draftF(10 + draftPicked) = 1
        draftAllyCount = draftAllyCount + 1
      else
        draftF(20 + draftPicked) = 1
        draftEnemyCount = draftEnemyCount + 1
      end if
    end if
  next draftPlayer
  draftF(30) = draftAllyCount / 5
  draftF(31) = draftEnemyCount / 5
  linear(draftF, draftWeights, draftBias, draftScores, 32, 10)
  draftBestClass = argmaxMasked(draftScores, draftF, 10)
  if draftBestClass >= 0 then
    draftHero(draftBestClass)
  end if
end sub

if drafting then
  chooseHero()
  end
end if

if battleStarted = 0 then
  battleStartTick = worldTick
  battleStarted = 1
end if
battleTick = worldTick - battleStartTick

if selfHp <= 0 then
  buybackCost = buybackPrice()
  if buybackCost > 0 and selfGold >= buybackCost then
    buyback()
  end if
  end
end if

' Spend every currently legal point. The trained actor favors W, then E/Q;
' take the ultimate whenever its level gate opens.
for upgrade = 1 to 4
  if canLevelAbility(3) then
    levelAbility(3)
  elseif canLevelAbility(1) then
    levelAbility(1)
  elseif canLevelAbility(2) then
    levelAbility(2)
  elseif canLevelAbility(0) then
    levelAbility(0)
  end if
next upgrade

dim f(27)
bestId = 0
bestDistance = 2147483647
objectiveId = 0
objectiveKind = 0
siegeThreatId = 0
siegeThreatHp = 2147483647
objectiveDistance = 2147483647
heroId = 0
heroDistance = 2147483647
enemyX = selfX
enemyY = selfY
enemyHp = 0
enemyKind = 0
enemyAttackTarget = 0
routeOpeningX = 71
routeOpeningY = 12
if selfTeam = 1 then
  routeOpeningX = 45
  routeOpeningY = 104
end if
routeGroupCount = 0
if selfTeam = 0 then
  gateHomeX = 105
  gateHomeY = 10
else
  gateHomeX = 10
  gateHomeY = 105
end if
gateThreatDistance = 2147483647
gateThreatSeen = 0
gateThreatX = gateHomeX
reserveHome = 0
allyCount = 0
allyX = 0
allyY = 0
maxAllyDistance = 0
index = 0
while index < objectCount()
  if objectAlive(index) then
    if objectTeam(index) = selfTeam and objectKind(index) = 1 then
      reserveHome = 1
      reserveHomeId = objectId(index)
      reserveX = objectX(index)
      reserveY = objectY(index)
    end if
    if objectTeam(index) = selfTeam and objectKind(index) = 2 then
      allyCount = allyCount + 1
      routeDx = objectX(index) - routeOpeningX
      routeDy = objectY(index) - routeOpeningY
      if routeDx * routeDx + routeDy * routeDy <= 16 then
        routeGroupCount = routeGroupCount + 1
      end if
      allyX = allyX + objectX(index)
      allyY = allyY + objectY(index)
      dx = objectX(index) - selfX
      dy = objectY(index) - selfY
      distance = dx * dx + dy * dy
      if distance > maxAllyDistance then
        maxAllyDistance = distance
      end if
    end if
    if objectTeam(index) <> selfTeam then
      if battleTick < 1000 and (objectKind(index) = 2 or objectKind(index) = 3) then
        gateDx = objectX(index) - gateHomeX
        gateDy = objectY(index) - gateHomeY
        gateDistance = gateDx * gateDx + gateDy * gateDy
        if gateDistance < gateThreatDistance then
          gateThreatDistance = gateDistance
          gateThreatSeen = 1
          gateThreatX = objectX(index)
        end if
      end if
      dx = objectX(index) - selfX
      dy = objectY(index) - selfY
      distance = dx * dx + dy * dy
      if distance < bestDistance then
        bestDistance = distance
        bestId = objectId(index)
        enemyX = objectX(index)
        enemyY = objectY(index)
        enemyHp = objectHp(index)
        enemyKind = objectKind(index)
        enemyAttackTarget = objectTarget(index)
      end if
      if objectKind(index) = 2 and objectTarget(index) = selfId then
        siegeRange = selfAttackRange \ 1000
        if distance * 3600 <= siegeRange * siegeRange and objectHp(index) < siegeThreatHp then
          siegeThreatId = objectId(index)
          siegeThreatHp = objectHp(index)
        end if
      end if
      if objectKind(index) = 1 or objectKind(index) = 4 then
        if distance < objectiveDistance then
          objectiveDistance = distance
          objectiveId = objectId(index)
          objectiveKind = objectKind(index)
        end if
      end if
      if objectKind(index) = 2 and distance < heroDistance then
        heroDistance = distance
        heroId = objectId(index)
        ringHeroX = objectX(index)
        ringHeroY = objectY(index)
        ringHeroTarget = objectTarget(index)
      end if
    end if
  end if
  index = index + 1
wend
if allyCount > 0 then
  allyX = allyX \ allyCount
  allyY = allyY \ allyCount
else
  allyX = selfX
  allyY = selfY
end if
f(0) = selfHp * 100 \ selfMaxHp
f(1) = 0
if selfMaxMana > 0 then
  f(1) = selfMana * 100 \ selfMaxMana
end if
f(2) = maxAllyDistance \ 100
f(3) = selfLevel * 5
f(4) = allyX - selfX
f(5) = allyY - selfY
f(6) = enemyX - selfX
f(7) = enemyY - selfY
f(8) = enemyHp \ 10
f(9) = enemyKind * 25
if selfTeam = 1 then
  f(4) = 0 - f(4)
  f(5) = 0 - f(5)
  f(6) = 0 - f(6)
  f(7) = 0 - f(7)
end if
f(10) = battleTick \ 288
f(11) = abilityCharges(0) * 25
f(12) = abilityCharges(1) * 25
f(13) = abilityCharges(2) * 25
f(14) = abilityCharges(3) * 25
f(15 + selfClass) = 100
f(25) = battleTick \ 16
if battleTick < 1000 and gateThreatSeen = 1 then
  gateEarlyThreatX = gateThreatX
  gateEarlyThreatSeen = 1
end if
f(26) = 0
if gateEarlyThreatSeen = 1 then
  f(26) = gateEarlyThreatX - gateHomeX
  if selfTeam = 1 then
    f(26) = 0 - f(26)
  end if
end if
index = 0
while index < 27
  if f(index) > 100 then
    f(index) = 100
  end if
  if f(index) < -100 then
    f(index) = -100
  end if
  index = index + 1
wend
dim h(16)
neuralActionCountdown = neuralActionCountdown - 1
if neuralActionCountdown <= 0 then
  neuralActionCountdown = 4
  linear(f, encoder, encoderBias, h, 25, 16)
  relu(h, 16)
  linear(h, decoder, decoderBias, logits, 16, 18)
  decision = argmax(logits, 18)
  ' Preserve the original sentinel edge case for int32 wraparound.
  if logits(decision) <= -2147483647 then
    decision = 0
  end if
end if
if decision = 18 then
  combatDecision = 8
else
combatDecision = decision
end if
objectiveBuild = 0
if decision >= 9 then
  combatDecision = decision - 9
  objectiveBuild = 1
end if

routeFallback = 0
if combatDecision = 2 or (combatDecision = 8 and bestId = 0) then
  if (objectiveId = 0 or objectiveDistance > 300) and (heroId = 0 or heroDistance > 700) then
    routeFallback = 1
  end if
end if
routeDx = selfX - routeOpeningX
routeDy = selfY - routeOpeningY
if battleTick < 3500 and routeFallback and routeGroupCount >= 3 then
  if routeDx * routeDx + routeDy * routeDy <= 16 then
    groupDeparture = 1
  end if
end if

if combatDecision = 8 then
  if objectiveId <> 0 and objectiveDistance <= 300 then
    attackTarget(objectiveId)
  else
    if heroId <> 0 and heroDistance <= 700 then
      attackTarget(heroId)
    else
      if bestId <> 0 then
        attackTarget(bestId)
      else
        if selfTeam = 0 then
          if battleTick < 3500 and groupDeparture = 0 then
            walkTo(71, 12)
          else
            if battleTick < 4500 then
              walkTo(9, 33)
            else
              walkTo(11, 106)
            end if
          end if
        else
          if battleTick < 3500 and groupDeparture = 0 then
            walkTo(45, 104)
          else
            if battleTick < 4500 then
              walkTo(107, 83)
            else
              walkTo(105, 10)
            end if
          end if
        end if
      end if
    end if
  end if
else
  if bestId <> 0 then
    attackTarget(bestId)
  else
    walkTo(64, 64)
  end if
end if
if selfClass = 7 and heroId <> 0 and ringHeroTarget = selfId then
  if heroDistance > 25 and heroDistance <= 49 then
    castPoint(3, (selfX + ringHeroX) \ 2, (selfY + ringHeroY) \ 2)
  end if
end if
hasHeal = 0
elixirCount = 0
hasMana = 0
hasPoison = 0
hasGear = 0
hasDagger = 0
hasSword = 0
hasArmor = 0
hasAxe = 0
hasBook = 0
emptySlot = 0
slot = 0
while slot < 6
  id = itemId(slot)
  if id = 0 then
    emptySlot = 1
  end if
  if id = 1 or id = 2 then
    hasHeal = 1
    if selfHp * 5 < selfMaxHp * 3 and itemCooldown(slot) = 0 then
      useItem(slot)
    end if
  end if
  if id = 2 then
    elixirCount = elixirCount + itemCount(slot)
  end if
  if id = 3 or id = 22 then
    hasMana = 1
    if objectiveBuild = 0 and selfMana * 5 < selfMaxMana * 2 and itemCooldown(slot) = 0 then
      useItem(slot)
    end if
  end if
  if id = 4 then
    hasPoison = 1
    if objectiveBuild = 0 and bestId <> 0 then
      useItem(slot)
    end if
  end if
  if id >= 5 and id <= 20 then
    hasGear = 1
  end if
  if id = 11 then
    hasDagger = 1
  end if
  if id = 13 then
    hasSword = 1
  end if
  if id = 16 then
    hasArmor = 1
  end if
  if id = 18 then
    hasAxe = 1
  end if
  if id = 20 then
    hasBook = 1
  end if
  slot = slot + 1
wend
if canShop() then
' Stock immediate healing after the opening build. Damage interrupts
' ordinary potion recovery, and a full six-slot pack cannot buy a cure.
if selfClass = 2 and selfLevel >= 4 and elixirCount < 3 then
  if selfGold >= 75 and (elixirCount > 0 or emptySlot <> 0) then
    buyItem(2)
    hasHeal = 1
  end if
end if
if selfHp * 2 < selfMaxHp and hasHeal = 0 then
  if selfGold >= 50 then
    buyItem(2)
  end if
  if selfGold >= 30 then
    buyItem(1)
  end if
end if
if objectiveBuild = 0 then
if selfMaxMana > 0 then
  if selfMana * 2 < selfMaxMana and hasMana = 0 then
    if selfGold >= 45 then
      buyItem(22)
    end if
  end if
end if
if bestId <> 0 and hasPoison = 0 then
  if selfGold >= 40 then
    buyItem(4)
  end if
end if
if emptySlot <> 0 then
  melee = 0
  ranged = 0
  magic = 0
  if selfClass = 0 or selfClass = 4 or selfClass = 5 or selfClass = 9 then
    melee = 1
  end if
  if selfClass = 1 or selfClass = 6 then
    ranged = 1
  end if
  if selfClass = 2 or selfClass = 3 or selfClass = 7 or selfClass = 8 then
    magic = 1
  end if
  if melee = 1 then
    if hasGear = 0 and selfGold >= 70 then
      buyItem(7)
    end if
    if selfGold >= 80 then
      buyItem(5)
    end if
    if selfGold >= 110 then
      buyItem(11)
    end if
    if selfGold >= 150 then
      buyItem(13)
    end if
    if selfGold >= 180 then
      buyItem(18)
    end if
  end if
  if ranged = 1 then
    if hasGear = 0 and selfGold >= 100 then
      buyItem(8)
    end if
    if selfGold >= 150 then
      buyItem(14)
    end if
    if selfGold >= 180 then
      buyItem(19)
    end if
  end if
  if magic = 1 then
    if hasGear = 0 and selfGold >= 140 then
      buyItem(12)
    end if
    if selfGold >= 120 then
      buyItem(10)
    end if
    if selfGold >= 170 then
      buyItem(17)
    end if
    if selfGold >= 190 then
      buyItem(20)
    end if
  end if
  if selfGold >= 90 then
    buyItem(6)
  end if
  if selfGold >= 120 then
    buyItem(9)
  end if
end if
else
  if emptySlot <> 0 then
    if hasDagger = 0 and selfGold >= 110 then
      buyItem(11)
    end if
    if hasSword = 0 and selfGold >= 150 then
      buyItem(13)
    end if
    if hasArmor = 0 and selfGold >= 160 then
      buyItem(16)
    end if
    if hasAxe = 0 and selfGold >= 180 then
      buyItem(18)
    end if
    if hasBook = 0 and selfGold >= 190 then
      buyItem(20)
    end if
  end if
end if
end if
if combatDecision = 1 then
  if selfTeam = 0 then
    walkTo(mapWidth - 10, 10)
  else
    walkTo(10, mapHeight - 10)
  end if
end if
if combatDecision = 2 then
  if objectiveId <> 0 and objectiveDistance <= 300 then
    attackTarget(objectiveId)
  else
    if heroId <> 0 and heroDistance <= 700 then
      attackTarget(heroId)
    else
      if selfTeam = 0 then
        if battleTick < 3500 and groupDeparture = 0 then
          walkTo(71, 12)
        else
          if battleTick < 4500 then
            walkTo(9, 33)
          else
            walkTo(11, 106)
          end if
        end if
      else
        if battleTick < 3500 and groupDeparture = 0 then
          walkTo(45, 104)
        else
          if battleTick < 4500 then
            walkTo(107, 83)
          else
            walkTo(105, 10)
          end if
        end if
      end if
    end if
  end if
end if
if combatDecision >= 3 and combatDecision <= 6 then
  if bestId <> 0 then
    castTarget(combatDecision - 3, bestId)
  else
    castTarget(combatDecision - 3, selfId)
  end if
end if
if combatDecision = 7 then
  walkTo(allyX, allyY)
end if

if decision = 18 and (bestId = 0 or bestDistance > 64) then
  specialistX = mapWidth - 1 - gateHomeX
  specialistY = gateHomeY
  specialistDx = selfX - specialistX
  specialistDy = selfY - specialistY
  if specialistDx * specialistDx + specialistDy * specialistDy <= 64 then
    perimeterStage = 1
  end if
  if perimeterStage <> 0 then
    specialistY = mapHeight - 1 - gateHomeY
  end if
  walkTo(specialistX, specialistY)
end if

if (combatDecision = 2 or combatDecision = 8) and objectiveKind = 4 and objectiveDistance <= 300 and siegeThreatId <> 0 then
  attackTarget(siegeThreatId)
end if

if reserveHome <> 0 then
  reserveGuards = 0
  reserveGuardCritical = 0
  reserveNearest = 1
  reserveDx = selfX - reserveX
  reserveDy = selfY - reserveY
  reserveDistance = reserveDx * reserveDx + reserveDy * reserveDy
  reserveTarget = 0
  reserveTargetDistance = 401
  reserveDirect = 0
  reserveDirectDistance = 401
  reserveHero = 0
  reserveHeroDistance = 401
  reserveFinish = 0
  reserveIndex = 0
  while reserveIndex < objectCount()
    reserveDx = objectX(reserveIndex) - reserveX
    reserveDy = objectY(reserveIndex) - reserveY
    reserveObjectHome = reserveDx * reserveDx + reserveDy * reserveDy
    if objectTeam(reserveIndex) = selfTeam then
      if objectKind(reserveIndex) = 4 and objectHp(reserveIndex) > 0 and reserveObjectHome <= 100 then
        reserveGuards = reserveGuards + 1
        if objectHp(reserveIndex) <= 780 then
          reserveGuardCritical = 1
        end if
      end if
      if objectKind(reserveIndex) = 2 and objectAlive(reserveIndex) and reserveObjectHome < reserveDistance then
        reserveNearest = 0
      end if
    else
      if objectAlive(reserveIndex) then
        if (objectKind(reserveIndex) = 2 or objectKind(reserveIndex) = 3) and reserveObjectHome < reserveDirectDistance then
          if objectTarget(reserveIndex) = reserveHomeId then
            reserveDirect = objectId(reserveIndex)
            reserveDirectDistance = reserveObjectHome
          end if
        end if
        if objectKind(reserveIndex) = 2 and reserveObjectHome < reserveHeroDistance then
          reserveHero = objectId(reserveIndex)
          reserveHeroDistance = reserveObjectHome
        end if
        if (objectKind(reserveIndex) = 2 or objectKind(reserveIndex) = 3) and reserveObjectHome < reserveTargetDistance then
          reserveTargetDistance = reserveObjectHome
          reserveTarget = objectId(reserveIndex)
        end if
        if objectKind(reserveIndex) = 1 and objectHp(reserveIndex) <= selfAttackDamage then
          reserveDx = objectX(reserveIndex) - selfX
          reserveDy = objectY(reserveIndex) - selfY
          reserveRange = selfAttackRange \ 1000
          if (reserveDx * reserveDx + reserveDy * reserveDy) * 3600 <= reserveRange * reserveRange then
            reserveFinish = 1
          end if
        end if
      end if
    end if
    reserveIndex = reserveIndex + 1
  wend
  if reserveHero <> 0 then
    reserveTarget = reserveHero
  end if
  if reserveDirect <> 0 then
    reserveTarget = reserveDirect
  end if
  if (reserveGuards <= 1 or (reserveGuardCritical <> 0 and reserveDistance <= 900)) and reserveNearest <> 0 and reserveFinish = 0 then
    if reserveDistance <= 400 and reserveTarget <> 0 then
      attackTarget(reserveTarget)
    else
      walkTo(reserveX, reserveY)
    end if
  end if
end if

if recoveryInitialized <> 0 and selfAttacksLanded > recoveryLastHit then
  walkTo(selfX, selfY)
end if
recoveryLastHit = selfAttacksLanded
recoveryInitialized = 1
